#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'


require 'journey/parser_extras'
module Journey
  class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    12,    14,    13,     6,    16,    15,     7,    12,    14,    13,
     6,    14,    15,     7,    12,    14,    13,     6,    20,    15,
     7,    21 ]

racc_action_check = [
     0,     0,     0,     0,     1,     0,     0,     2,     2,     2,
     2,     7,     2,     2,     6,     6,     6,     6,    16,     6,
     6,    18 ]

racc_action_pointer = [
    -2,     4,     5,   nil,   nil,   nil,    12,     8,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    18,   nil,    15,   nil,
   nil,   nil ]

racc_action_default = [
   -16,   -16,    -1,    -3,    -4,    -5,   -16,   -16,    -8,    -9,
   -10,   -11,   -12,   -13,   -14,   -15,   -16,    -2,   -16,    -7,
    22,    -6 ]

racc_goto_table = [
     1,    19,    17,   nil,   nil,   nil,    18 ]

racc_goto_check = [
     1,     6,     1,   nil,   nil,   nil,     1 ]

racc_goto_pointer = [
   nil,     0,   nil,   nil,   nil,   nil,    -6,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,     9,     8,    10,    11 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 10, :_reduce_1,
  2, 10, :_reduce_2,
  1, 11, :_reduce_none,
  1, 11, :_reduce_none,
  1, 11, :_reduce_none,
  3, 13, :_reduce_6,
  2, 14, :_reduce_7,
  1, 12, :_reduce_none,
  1, 12, :_reduce_none,
  1, 12, :_reduce_none,
  1, 12, :_reduce_none,
  1, 17, :_reduce_12,
  1, 16, :_reduce_13,
  1, 15, :_reduce_14,
  1, 18, :_reduce_15 ]

racc_reduce_n = 16

racc_shift_n = 22

racc_token_table = {
  false => 0,
  :error => 1,
  :SLASH => 2,
  :LITERAL => 3,
  :SYMBOL => 4,
  :LPAREN => 5,
  :RPAREN => 6,
  :DOT => 7,
  :STAR => 8 }

racc_nt_base = 9

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SLASH",
  "LITERAL",
  "SYMBOL",
  "LPAREN",
  "RPAREN",
  "DOT",
  "STAR",
  "$start",
  "expressions",
  "expression",
  "terminal",
  "group",
  "star",
  "literal",
  "symbol",
  "slash",
  "dot" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 result = val.first 
    result
end

def _reduce_2(val, _values, result)
 result = Cat.new(val) 
    result
end

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
 result = Group.new([val[1]]) 
    result
end

def _reduce_7(val, _values, result)
 result = Star.new([Symbol.new(val.last.children)]) 
    result
end

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

def _reduce_12(val, _values, result)
 result = Slash.new('/') 
    result
end

def _reduce_13(val, _values, result)
 result = Symbol.new(val.first) 
    result
end

def _reduce_14(val, _values, result)
 result = Literal.new(val.first) 
    result
end

def _reduce_15(val, _values, result)
 result = Dot.new(val.first) 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Journey
